#!/usr/bin/env python3
"""
mic_wire.py — wire generated mic pages into the KB surfaces.

Rewrites, idempotently:
  1. A "Locker Gallery" block in Wiki/mic-library.md — a thumbnail card grid
     (grouped by category) where each card links to /mic-<slug>. Thumbnails load
     via CSS background-image, so a missing photo shows a clean navy placeholder
     instead of a broken-image icon. Delimited by MIC-GALLERY markers.
  2. Linkifies plain mic names in the go-to category tables to their pages.
Nav (kb-nav.json) and index.md keep pointing at Mic Library; the gallery is the
click surface, so the sidebar doesn't bloat with ~50 entries.

Called by mic_page_gen.py --wire, or standalone:
    python3 mic_wire.py --data mic_data.json
"""
import json, os, re, argparse

KB = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WIKI = os.path.join(KB, "Wiki")
LIB = os.path.join(WIKI, "mic-library.md")

START = "<!-- MIC-GALLERY:START (generated by mic_wire.py — edit records, not here) -->"
END = "<!-- MIC-GALLERY:END -->"

CAT_ORDER = ["Dynamic", "Small Diaphragm Condenser", "Large Diaphragm Condenser",
             "Ribbon", "Lavalier", "DI", "Preamp"]

def card(m):
    slug, name = m["slug"], m["name"]
    thumb = f"/assets/mics/{slug}/{slug}-thumb.jpg"
    owned = m.get("owned", True)
    ring = "#2E6DA4" if owned else "#9AA6B2"
    return (
        f'<a href="/mic-{slug}" title="{name}" '
        f'style="display:inline-block;width:150px;margin:6px;text-align:center;'
        f'text-decoration:none;vertical-align:top;">'
        f'<div style="width:150px;height:110px;border-radius:8px;'
        f"background:#1A3A5C url('{thumb}') center/cover no-repeat;"
        f'border:1px solid {ring};"></div>'
        f'<div style="font-size:12px;color:#1A3A5C;margin-top:3px;'
        f'line-height:1.2;">{name}</div></a>'
    )

def gallery_block(mics):
    by_cat = {}
    for m in mics:
        by_cat.setdefault(m["category"], []).append(m)
    lines = [START, "", "## Locker Gallery", "",
             "_Click any mic for its full spec sheet + reference PDF. "
             "Faded ring = reference (not in the locker)._", ""]
    cats = [c for c in CAT_ORDER if c in by_cat] + \
           [c for c in by_cat if c not in CAT_ORDER]
    for c in cats:
        lines.append(f"**{c}**")
        lines.append("")
        lines.append('<div style="display:flex;flex-wrap:wrap;align-items:flex-start;">')
        for m in sorted(by_cat[c], key=lambda x: x["name"].lower()):
            lines.append(card(m))
        lines.append("</div>")
        lines.append("")
    lines.append(END)
    return "\n".join(lines)

def linkify_tables(text, mics):
    """Wrap plain mic names in go-to tables with a link, once, if not already linked."""
    for m in sorted(mics, key=lambda x: -len(x["name"])):
        name = m["name"]
        slug = m["slug"]
        # match a table cell that is exactly the name (start of a row), not already a link
        pat = re.compile(r'(?m)^\| ' + re.escape(name) + r' (\|)')
        repl = f'| [{name}](/mic-{slug}) \\1'
        text = pat.sub(repl, text)
    return text

def wire_all(mics):
    text = open(LIB).read()
    block = gallery_block(mics)
    if START in text and END in text:
        text = re.sub(re.escape(START) + r".*?" + re.escape(END), block,
                      text, flags=re.S)
    else:
        # insert after the Overview shorthands line (before first '---' after Overview)
        anchor = "\n---\n\n## Dynamics"
        if anchor in text:
            text = text.replace(anchor, "\n---\n\n" + block + "\n\n---\n\n## Dynamics", 1)
        else:
            text += "\n\n" + block + "\n"
    text = linkify_tables(text, mics)
    with open(LIB, "w") as f:
        f.write(text)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--data", required=True)
    a = ap.parse_args()
    d = json.load(open(a.data))
    wire_all(d["mics"] if isinstance(d, dict) else d)
    print("wired.")
