server {
    listen 80;
    location /assets/ {
        alias /wiki-data/content/repo/assets/;
        autoindex off;
        add_header Content-Disposition attachment;
    }
    location / {
        return 404;
    }
}
